// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";

export interface IBlogFields {
  /** title */
  title: string;

  /** spoiler */
  spoiler: string;

  /** length */
  length?: number | undefined;

  /** contentMarkdown */
  contentMarkdown: string;

  /** slug */
  slug: string;

  /** publishDate */
  publishDate?: string | undefined;
}

export interface IBlog extends Entry<IBlogFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blog";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "blog";

export type IEntry = IBlog;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
